//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Iot.Debug {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Iot.Debug.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ DaHttp ] 的本地化字符串。
        /// </summary>
        internal static string DaHttp {
            get {
                return ResourceManager.GetString("DaHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        internal static string Daq {
            get {
                return ResourceManager.GetString("Daq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集服务端 的本地化字符串。
        /// </summary>
        internal static string DaqService {
            get {
                return ResourceManager.GetString("DaqService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Da客户端 ] 的本地化字符串。
        /// </summary>
        internal static string Da客户端 {
            get {
                return ResourceManager.GetString("Da客户端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 数据库 ] 的本地化字符串。
        /// </summary>
        internal static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFmpeg 工具路径，下载地址：https://github.com/BtbN/FFmpeg-Builds/releases 的本地化字符串。
        /// </summary>
        internal static string FFmpeg_工具路径 {
            get {
                return ResourceManager.GetString("FFmpeg 工具路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Gif ] 的本地化字符串。
        /// </summary>
        internal static string Gif {
            get {
                return ResourceManager.GetString("Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Kafka ] 的本地化字符串。
        /// </summary>
        internal static string Kafka {
            get {
                return ResourceManager.GetString("Kafka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ LSis ] 的本地化字符串。
        /// </summary>
        internal static string LSis {
            get {
                return ResourceManager.GetString("LSis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Modbus ] 的本地化字符串。
        /// </summary>
        internal static string Modbus {
            get {
                return ResourceManager.GetString("Modbus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输 的本地化字符串。
        /// </summary>
        internal static string Mq {
            get {
                return ResourceManager.GetString("Mq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输服务端 的本地化字符串。
        /// </summary>
        internal static string MqService {
            get {
                return ResourceManager.GetString("MqService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Mqtt ] 的本地化字符串。
        /// </summary>
        internal static string Mqtt {
            get {
                return ResourceManager.GetString("Mqtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Mqtt客户端 ] 的本地化字符串。
        /// </summary>
        internal static string MqttClient {
            get {
                return ResourceManager.GetString("MqttClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Mqtt服务端 ] 的本地化字符串。
        /// </summary>
        internal static string MqttService {
            get {
                return ResourceManager.GetString("MqttService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ MqttWs服务端 ] 的本地化字符串。
        /// </summary>
        internal static string MqttWsService {
            get {
                return ResourceManager.GetString("MqttWsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ NetMQ ] 的本地化字符串。
        /// </summary>
        internal static string NetMQ {
            get {
                return ResourceManager.GetString("NetMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Netty ] 的本地化字符串。
        /// </summary>
        internal static string Netty {
            get {
                return ResourceManager.GetString("Netty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Netty客户端 ] 的本地化字符串。
        /// </summary>
        internal static string NettyClient {
            get {
                return ResourceManager.GetString("NettyClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Netty服务端 ] 的本地化字符串。
        /// </summary>
        internal static string NettyService {
            get {
                return ResourceManager.GetString("NettyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcDa ] 的本地化字符串。
        /// </summary>
        internal static string OpcDa {
            get {
                return ResourceManager.GetString("OpcDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcDaHttp ] 的本地化字符串。
        /// </summary>
        internal static string OpcDaHttp {
            get {
                return ResourceManager.GetString("OpcDaHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcUa ] 的本地化字符串。
        /// </summary>
        internal static string OpcUa {
            get {
                return ResourceManager.GetString("OpcUa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcUa 节点浏览 ] 的本地化字符串。
        /// </summary>
        internal static string OpcUaNodeBrowsing {
            get {
                return ResourceManager.GetString("OpcUaNodeBrowsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcUa服务端 ] 的本地化字符串。
        /// </summary>
        internal static string OpcUaService {
            get {
                return ResourceManager.GetString("OpcUaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ OpcUa服务端 ] 的本地化字符串。
        /// </summary>
        internal static string OpcUaServiceToolTitle {
            get {
                return ResourceManager.GetString("OpcUaServiceToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ RabbitMQ ] 的本地化字符串。
        /// </summary>
        internal static string RabbitMQ {
            get {
                return ResourceManager.GetString("RabbitMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ RocketMQ ] 的本地化字符串。
        /// </summary>
        internal static string RocketMQ {
            get {
                return ResourceManager.GetString("RocketMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 串口 ] 的本地化字符串。
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 采集模拟 ] 的本地化字符串。
        /// </summary>
        internal static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Svg ] 的本地化字符串。
        /// </summary>
        internal static string Svg {
            get {
                return ResourceManager.GetString("Svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Svg代码 的本地化字符串。
        /// </summary>
        internal static string Svg代码 {
            get {
                return ResourceManager.GetString("Svg代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Svg转换工具 的本地化字符串。
        /// </summary>
        internal static string Svg转换工具 {
            get {
                return ResourceManager.GetString("Svg转换工具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Snet.cn ] Iot 调试工具 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Tcp ] 的本地化字符串。
        /// </summary>
        internal static string Tcp {
            get {
                return ResourceManager.GetString("Tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Tcp客户端 ] 的本地化字符串。
        /// </summary>
        internal static string TcpClient {
            get {
                return ResourceManager.GetString("TcpClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Tcp服务端 ] 的本地化字符串。
        /// </summary>
        internal static string TcpService {
            get {
                return ResourceManager.GetString("TcpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ TCP扩展插件 ] 的本地化字符串。
        /// </summary>
        internal static string TEP {
            get {
                return ResourceManager.GetString("TEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ua客户端 ] 的本地化字符串。
        /// </summary>
        internal static string Ua客户端 {
            get {
                return ResourceManager.GetString("Ua客户端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ua服务端 ] 的本地化字符串。
        /// </summary>
        internal static string Ua服务端 {
            get {
                return ResourceManager.GetString("Ua服务端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Udp广播 ] 的本地化字符串。
        /// </summary>
        internal static string UdpBroadcast {
            get {
                return ResourceManager.GetString("UdpBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Udp客户端 ] 的本地化字符串。
        /// </summary>
        internal static string UdpClient {
            get {
                return ResourceManager.GetString("UdpClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Udp组播 ] 的本地化字符串。
        /// </summary>
        internal static string UdpMulticast {
            get {
                return ResourceManager.GetString("UdpMulticast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Udp服务端 ] 的本地化字符串。
        /// </summary>
        internal static string UdpService {
            get {
                return ResourceManager.GetString("UdpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ws ] 的本地化字符串。
        /// </summary>
        internal static string Ws {
            get {
                return ResourceManager.GetString("Ws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ws客户端 ] 的本地化字符串。
        /// </summary>
        internal static string WsClient {
            get {
                return ResourceManager.GetString("WsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ws服务端 ] 的本地化字符串。
        /// </summary>
        internal static string WsService {
            get {
                return ResourceManager.GetString("WsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Ws服务端 ] 的本地化字符串。
        /// </summary>
        internal static string Ws服务端 {
            get {
                return ResourceManager.GetString("Ws服务端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo ] 的本地化字符串。
        /// </summary>
        internal static string Yolo {
            get {
                return ResourceManager.GetString("Yolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 分类 ] 的本地化字符串。
        /// </summary>
        internal static string YoloClassify {
            get {
                return ResourceManager.GetString("YoloClassify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 检测 ] 的本地化字符串。
        /// </summary>
        internal static string YoloDetect {
            get {
                return ResourceManager.GetString("YoloDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 定向检测 ] 的本地化字符串。
        /// </summary>
        internal static string YoloOBB {
            get {
                return ResourceManager.GetString("YoloOBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 姿态 ] 的本地化字符串。
        /// </summary>
        internal static string YoloPose {
            get {
                return ResourceManager.GetString("YoloPose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 分割 ] 的本地化字符串。
        /// </summary>
        internal static string YoloSegment {
            get {
                return ResourceManager.GetString("YoloSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 三菱 ] 的本地化字符串。
        /// </summary>
        internal static string 三菱 {
            get {
                return ResourceManager.GetString("三菱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许移除 的本地化字符串。
        /// </summary>
        internal static string 不允许移除 {
            get {
                return ResourceManager.GetString("不允许移除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的 Hex 数据 的本地化字符串。
        /// </summary>
        internal static string 不是有效的_Hex_数据 {
            get {
                return ResourceManager.GetString("不是有效的 Hex 数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 东方马达 ] 的本地化字符串。
        /// </summary>
        internal static string 东方马达 {
            get {
                return ResourceManager.GetString("东方马达", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个 的本地化字符串。
        /// </summary>
        internal static string 个 {
            get {
                return ResourceManager.GetString("个", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 丰炜 ] 的本地化字符串。
        /// </summary>
        internal static string 丰炜 {
            get {
                return ResourceManager.GetString("丰炜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 丰田 ] 的本地化字符串。
        /// </summary>
        internal static string 丰田 {
            get {
                return ResourceManager.GetString("丰田", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        internal static string 串口 {
            get {
                return ResourceManager.GetString("串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string 主题 {
            get {
                return ResourceManager.GetString("主题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交互 的本地化字符串。
        /// </summary>
        internal static string 交互 {
            get {
                return ResourceManager.GetString("交互", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交并比阈值 的本地化字符串。
        /// </summary>
        internal static string 交并比阈值 {
            get {
                return ResourceManager.GetString("交并比阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string 信息 {
            get {
                return ResourceManager.GetString("信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息事件 的本地化字符串。
        /// </summary>
        internal static string 信息事件 {
            get {
                return ResourceManager.GetString("信息事件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 信捷 ] 的本地化字符串。
        /// </summary>
        internal static string 信捷 {
            get {
                return ResourceManager.GetString("信捷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 倍福 ] 的本地化字符串。
        /// </summary>
        internal static string 倍福 {
            get {
                return ResourceManager.GetString("倍福", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string 值 {
            get {
                return ResourceManager.GetString("值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止验证 的本地化字符串。
        /// </summary>
        internal static string 停止验证 {
            get {
                return ResourceManager.GetString("停止验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素置信度阈值 的本地化字符串。
        /// </summary>
        internal static string 像素置信度阈值 {
            get {
                return ResourceManager.GetString("像素置信度阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常捕获 的本地化字符串。
        /// </summary>
        internal static string 全局异常捕获 {
            get {
                return ResourceManager.GetString("全局异常捕获", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部关闭 的本地化字符串。
        /// </summary>
        internal static string 全部关闭 {
            get {
                return ResourceManager.GetString("全部关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其他 的本地化字符串。
        /// </summary>
        internal static string 关闭其他 {
            get {
                return ResourceManager.GetString("关闭其他", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string 内容 {
            get {
                return ResourceManager.GetString("内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        internal static string 写入 {
            get {
                return ResourceManager.GetString("写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据 的本地化字符串。
        /// </summary>
        internal static string 写入数据 {
            get {
                return ResourceManager.GetString("写入数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准度 的本地化字符串。
        /// </summary>
        internal static string 准度 {
            get {
                return ResourceManager.GetString("准度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类数量 的本地化字符串。
        /// </summary>
        internal static string 分类数量 {
            get {
                return ResourceManager.GetString("分类数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string 创建 {
            get {
                return ResourceManager.GetString("创建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建父级 的本地化字符串。
        /// </summary>
        internal static string 创建父级 {
            get {
                return ResourceManager.GetString("创建父级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能 的本地化字符串。
        /// </summary>
        internal static string 功能 {
            get {
                return ResourceManager.GetString("功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态随机变化地址 的本地化字符串。
        /// </summary>
        internal static string 动态随机变化地址 {
            get {
                return ResourceManager.GetString("动态随机变化地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态随机范围变化地址 的本地化字符串。
        /// </summary>
        internal static string 动态随机范围变化地址 {
            get {
                return ResourceManager.GetString("动态随机范围变化地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态顺序变化地址 的本地化字符串。
        /// </summary>
        internal static string 动态顺序变化地址 {
            get {
                return ResourceManager.GetString("动态顺序变化地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态顺序范围变化地址 的本地化字符串。
        /// </summary>
        internal static string 动态顺序范围变化地址 {
            get {
                return ResourceManager.GetString("动态顺序范围变化地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始图片 的本地化字符串。
        /// </summary>
        internal static string 原始图片 {
            get {
                return ResourceManager.GetString("原始图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始图片路径 的本地化字符串。
        /// </summary>
        internal static string 原始图片路径 {
            get {
                return ResourceManager.GetString("原始图片路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string 参数 {
            get {
                return ResourceManager.GetString("参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布 的本地化字符串。
        /// </summary>
        internal static string 发布 {
            get {
                return ResourceManager.GetString("发布", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string 发送 {
            get {
                return ResourceManager.GetString("发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送等待 的本地化字符串。
        /// </summary>
        internal static string 发送等待 {
            get {
                return ResourceManager.GetString("发送等待", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 发那科 ] 的本地化字符串。
        /// </summary>
        internal static string 发那科 {
            get {
                return ResourceManager.GetString("发那科", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订阅 的本地化字符串。
        /// </summary>
        internal static string 取消订阅 {
            get {
                return ResourceManager.GetString("取消订阅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 台达 ] 的本地化字符串。
        /// </summary>
        internal static string 台达 {
            get {
                return ResourceManager.GetString("台达", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上验证 的本地化字符串。
        /// </summary>
        internal static string 向上验证 {
            get {
                return ResourceManager.GetString("向上验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下验证 的本地化字符串。
        /// </summary>
        internal static string 向下验证 {
            get {
                return ResourceManager.GetString("向下验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 图尔克 ] 的本地化字符串。
        /// </summary>
        internal static string 图尔克 {
            get {
                return ResourceManager.GetString("图尔克", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表 的本地化字符串。
        /// </summary>
        internal static string 图表 {
            get {
                return ResourceManager.GetString("图表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string 地址 {
            get {
                return ResourceManager.GetString("地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址操作 的本地化字符串。
        /// </summary>
        internal static string 地址操作 {
            get {
                return ResourceManager.GetString("地址操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址类型 的本地化字符串。
        /// </summary>
        internal static string 地址类型 {
            get {
                return ResourceManager.GetString("地址类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标 的本地化字符串。
        /// </summary>
        internal static string 坐标 {
            get {
                return ResourceManager.GetString("坐标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 基恩士 ] 的本地化字符串。
        /// </summary>
        internal static string 基恩士 {
            get {
                return ResourceManager.GetString("基恩士", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础数据 的本地化字符串。
        /// </summary>
        internal static string 基础数据 {
            get {
                return ResourceManager.GetString("基础数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string 复制 {
            get {
                return ResourceManager.GetString("复制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制地址名称 的本地化字符串。
        /// </summary>
        internal static string 复制地址名称 {
            get {
                return ResourceManager.GetString("复制地址名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制结果 的本地化字符串。
        /// </summary>
        internal static string 复制结果 {
            get {
                return ResourceManager.GetString("复制结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string 大小 {
            get {
                return ResourceManager.GetString("大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径 的本地化字符串。
        /// </summary>
        internal static string 存储路径 {
            get {
                return ResourceManager.GetString("存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 宇电 ] 的本地化字符串。
        /// </summary>
        internal static string 宇电 {
            get {
                return ResourceManager.GetString("宇电", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 安川 ] 的本地化字符串。
        /// </summary>
        internal static string 安川 {
            get {
                return ResourceManager.GetString("安川", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        internal static string 客户端 {
            get {
                return ResourceManager.GetString("客户端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端列表 的本地化字符串。
        /// </summary>
        internal static string 客户端列表 {
            get {
                return ResourceManager.GetString("客户端列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 富士 ] 的本地化字符串。
        /// </summary>
        internal static string 富士 {
            get {
                return ResourceManager.GetString("富士", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对应硬件的JSON字符串 的本地化字符串。
        /// </summary>
        internal static string 对应硬件的JSON字符串 {
            get {
                return ResourceManager.GetString("对应硬件的JSON字符串", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string 导入 {
            get {
                return ResourceManager.GetString("导入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败 的本地化字符串。
        /// </summary>
        internal static string 导入失败 {
            get {
                return ResourceManager.GetString("导入失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        internal static string 导入成功 {
            get {
                return ResourceManager.GetString("导入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入节点 的本地化字符串。
        /// </summary>
        internal static string 导入节点 {
            get {
                return ResourceManager.GetString("导入节点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string 导出 {
            get {
                return ResourceManager.GetString("导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出节点 的本地化字符串。
        /// </summary>
        internal static string 导出节点 {
            get {
                return ResourceManager.GetString("导出节点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 山武 ] 的本地化字符串。
        /// </summary>
        internal static string 山武 {
            get {
                return ResourceManager.GetString("山武", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string 工具 {
            get {
                return ResourceManager.GetString("工具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 的本地化字符串。
        /// </summary>
        internal static string 已加载 {
            get {
                return ResourceManager.GetString("已加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消 的本地化字符串。
        /// </summary>
        internal static string 已取消 {
            get {
                return ResourceManager.GetString("已取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动 的本地化字符串。
        /// </summary>
        internal static string 已启动 {
            get {
                return ResourceManager.GetString("已启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始统计 的本地化字符串。
        /// </summary>
        internal static string 开始统计 {
            get {
                return ResourceManager.GetString("开始统计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张原图 的本地化字符串。
        /// </summary>
        internal static string 张原图 {
            get {
                return ResourceManager.GetString("张原图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 性能测试 ] 的本地化字符串。
        /// </summary>
        internal static string 性能测试 {
            get {
                return ResourceManager.GetString("性能测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string 打开 {
            get {
                return ResourceManager.GetString("打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string 描述 {
            get {
                return ResourceManager.GetString("描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  搜索 的本地化字符串。
        /// </summary>
        internal static string 搜索 {
            get {
                return ResourceManager.GetString("搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string 数据 {
            get {
                return ResourceManager.GetString("数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不能为空 的本地化字符串。
        /// </summary>
        internal static string 数据不能为空 {
            get {
                return ResourceManager.GetString("数据不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据事件 的本地化字符串。
        /// </summary>
        internal static string 数据事件 {
            get {
                return ResourceManager.GetString("数据事件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格式不正确 的本地化字符串。
        /// </summary>
        internal static string 数据格式不正确 {
            get {
                return ResourceManager.GetString("数据格式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        internal static string 数据类型 {
            get {
                return ResourceManager.GetString("数据类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        internal static string 文件路径 {
            get {
                return ResourceManager.GetString("文件路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 服务端 ] 的本地化字符串。
        /// </summary>
        internal static string 服务端 {
            get {
                return ResourceManager.GetString("服务端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启动 的本地化字符串。
        /// </summary>
        internal static string 未启动 {
            get {
                return ResourceManager.GetString("未启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检索到图片 的本地化字符串。
        /// </summary>
        internal static string 未检索到图片 {
            get {
                return ResourceManager.GetString("未检索到图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 松下 ] 的本地化字符串。
        /// </summary>
        internal static string 松下 {
            get {
                return ResourceManager.GetString("松下", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查阅 的本地化字符串。
        /// </summary>
        internal static string 查阅 {
            get {
                return ResourceManager.GetString("查阅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string 标签 {
            get {
                return ResourceManager.GetString("标签", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型路径 的本地化字符串。
        /// </summary>
        internal static string 模型路径 {
            get {
                return ResourceManager.GetString("模型路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 横河 ] 的本地化字符串。
        /// </summary>
        internal static string 横河 {
            get {
                return ResourceManager.GetString("横河", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 欧姆龙 ] 的本地化字符串。
        /// </summary>
        internal static string 欧姆龙 {
            get {
                return ResourceManager.GetString("欧姆龙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 永宏 ] 的本地化字符串。
        /// </summary>
        internal static string 永宏 {
            get {
                return ResourceManager.GetString("永宏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 汇川 ] 的本地化字符串。
        /// </summary>
        internal static string 汇川 {
            get {
                return ResourceManager.GetString("汇川", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释 的本地化字符串。
        /// </summary>
        internal static string 注释 {
            get {
                return ResourceManager.GetString("注释", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string 消息 {
            get {
                return ResourceManager.GetString("消息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级 的本地化字符串。
        /// </summary>
        internal static string 父级 {
            get {
                return ResourceManager.GetString("父级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级创建失败 的本地化字符串。
        /// </summary>
        internal static string 父级创建失败 {
            get {
                return ResourceManager.GetString("父级创建失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级创建成功 的本地化字符串。
        /// </summary>
        internal static string 父级创建成功 {
            get {
                return ResourceManager.GetString("父级创建成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级名称 的本地化字符串。
        /// </summary>
        internal static string 父级名称 {
            get {
                return ResourceManager.GetString("父级名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级名称不能为空 的本地化字符串。
        /// </summary>
        internal static string 父级名称不能为空 {
            get {
                return ResourceManager.GetString("父级名称不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级移除失败 的本地化字符串。
        /// </summary>
        internal static string 父级移除失败 {
            get {
                return ResourceManager.GetString("父级移除失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级移除成功 的本地化字符串。
        /// </summary>
        internal static string 父级移除成功 {
            get {
                return ResourceManager.GetString("父级移除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 理化 ] 的本地化字符串。
        /// </summary>
        internal static string 理化 {
            get {
                return ResourceManager.GetString("理化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时 的本地化字符串。
        /// </summary>
        internal static string 用时 {
            get {
                return ResourceManager.GetString("用时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 电力通讯规约 ] 的本地化字符串。
        /// </summary>
        internal static string 电力通讯规约 {
            get {
                return ResourceManager.GetString("电力通讯规约", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标 的本地化字符串。
        /// </summary>
        internal static string 目标 {
            get {
                return ResourceManager.GetString("目标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 科伺 ] 的本地化字符串。
        /// </summary>
        internal static string 科伺 {
            get {
                return ResourceManager.GetString("科伺", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        internal static string 移除 {
            get {
                return ResourceManager.GetString("移除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除数据 的本地化字符串。
        /// </summary>
        internal static string 移除数据 {
            get {
                return ResourceManager.GetString("移除数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除父级 的本地化字符串。
        /// </summary>
        internal static string 移除父级 {
            get {
                return ResourceManager.GetString("移除父级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string 端口 {
            get {
                return ResourceManager.GetString("端口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string 类型 {
            get {
                return ResourceManager.GetString("类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束统计 的本地化字符串。
        /// </summary>
        internal static string 结束统计 {
            get {
                return ResourceManager.GetString("结束统计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 维控 ] 的本地化字符串。
        /// </summary>
        internal static string 维控 {
            get {
                return ResourceManager.GetString("维控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码类型 的本地化字符串。
        /// </summary>
        internal static string 编码类型 {
            get {
                return ResourceManager.GetString("编码类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 罗克韦尔 ] 的本地化字符串。
        /// </summary>
        internal static string 罗克韦尔 {
            get {
                return ResourceManager.GetString("罗克韦尔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置信度阈值 的本地化字符串。
        /// </summary>
        internal static string 置信度阈值 {
            get {
                return ResourceManager.GetString("置信度阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群发 的本地化字符串。
        /// </summary>
        internal static string 群发 {
            get {
                return ResourceManager.GetString("群发", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 自由协议 ] 的本地化字符串。
        /// </summary>
        internal static string 自由协议 {
            get {
                return ResourceManager.GetString("自由协议", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点 的本地化字符串。
        /// </summary>
        internal static string 节点 {
            get {
                return ResourceManager.GetString("节点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpcUa 节点信息浏览 的本地化字符串。
        /// </summary>
        internal static string 节点信息浏览 {
            get {
                return ResourceManager.GetString("节点信息浏览", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点信息浏览[隐藏/显示] 的本地化字符串。
        /// </summary>
        internal static string 节点信息浏览_隐藏_显示_ {
            get {
                return ResourceManager.GetString("节点信息浏览[隐藏/显示]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点加载失败 的本地化字符串。
        /// </summary>
        internal static string 节点加载失败 {
            get {
                return ResourceManager.GetString("节点加载失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点地址 的本地化字符串。
        /// </summary>
        internal static string 节点地址 {
            get {
                return ResourceManager.GetString("节点地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点已取消加载 的本地化字符串。
        /// </summary>
        internal static string 节点已取消加载 {
            get {
                return ResourceManager.GetString("节点已取消加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点成功导出至 的本地化字符串。
        /// </summary>
        internal static string 节点成功导出至 {
            get {
                return ResourceManager.GetString("节点成功导出至", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 英威腾 ] 的本地化字符串。
        /// </summary>
        internal static string 英威腾 {
            get {
                return ResourceManager.GetString("英威腾", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取对应类型参数 的本地化字符串。
        /// </summary>
        internal static string 获取对应类型参数 {
            get {
                return ResourceManager.GetString("获取对应类型参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取集合 的本地化字符串。
        /// </summary>
        internal static string 获取集合 {
            get {
                return ResourceManager.GetString("获取集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string 菜单 {
            get {
                return ResourceManager.GetString("菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 西蒙 ] 的本地化字符串。
        /// </summary>
        internal static string 西蒙 {
            get {
                return ResourceManager.GetString("西蒙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 西门子 ] 的本地化字符串。
        /// </summary>
        internal static string 西门子 {
            get {
                return ResourceManager.GetString("西门子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频转Gif 的本地化字符串。
        /// </summary>
        internal static string 视频转Gif {
            get {
                return ResourceManager.GetString("视频转Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订阅 的本地化字符串。
        /// </summary>
        internal static string 订阅 {
            get {
                return ResourceManager.GetString("订阅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问级别 的本地化字符串。
        /// </summary>
        internal static string 访问级别 {
            get {
                return ResourceManager.GetString("访问级别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        internal static string 详情 {
            get {
                return ResourceManager.GetString("详情", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先打开连接 的本地化字符串。
        /// </summary>
        internal static string 请先打开连接 {
            get {
                return ResourceManager.GetString("请先打开连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请把所有子节点都展开在进行导出操作 的本地化字符串。
        /// </summary>
        internal static string 请把所有子节点都展开在进行导出操作 {
            get {
                return ResourceManager.GetString("请把所有子节点都展开在进行导出操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选中节点后操作 的本地化字符串。
        /// </summary>
        internal static string 请选中节点后操作 {
            get {
                return ResourceManager.GetString("请选中节点后操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个已连接的客户端 的本地化字符串。
        /// </summary>
        internal static string 请选择一个已连接的客户端 {
            get {
                return ResourceManager.GetString("请选择一个已连接的客户端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件 的本地化字符串。
        /// </summary>
        internal static string 请选择文件 {
            get {
                return ResourceManager.GetString("请选择文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件夹 的本地化字符串。
        /// </summary>
        internal static string 请选择文件夹 {
            get {
                return ResourceManager.GetString("请选择文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择模型路径 的本地化字符串。
        /// </summary>
        internal static string 请选择模型路径 {
            get {
                return ResourceManager.GetString("请选择模型路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要验证图片的文件夹 的本地化字符串。
        /// </summary>
        internal static string 请选择需要验证图片的文件夹 {
            get {
                return ResourceManager.GetString("请选择需要验证图片的文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        internal static string 读取 {
            get {
                return ResourceManager.GetString("读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        internal static string 读取失败 {
            get {
                return ResourceManager.GetString("读取失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不能为空 的本地化字符串。
        /// </summary>
        internal static string 路径不能为空 {
            get {
                return ResourceManager.GetString("路径不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换 的本地化字符串。
        /// </summary>
        internal static string 转换 {
            get {
                return ResourceManager.GetString("转换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换失败 的本地化字符串。
        /// </summary>
        internal static string 转换失败 {
            get {
                return ResourceManager.GetString("转换失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换成功 的本地化字符串。
        /// </summary>
        internal static string 转换成功 {
            get {
                return ResourceManager.GetString("转换成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换结果 的本地化字符串。
        /// </summary>
        internal static string 转换结果 {
            get {
                return ResourceManager.GetString("转换结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续验证 的本地化字符串。
        /// </summary>
        internal static string 连续验证 {
            get {
                return ResourceManager.GetString("连续验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string 选择 {
            get {
                return ResourceManager.GetString("选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择存储路径 的本地化字符串。
        /// </summary>
        internal static string 选择存储路径 {
            get {
                return ResourceManager.GetString("选择存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件路径 的本地化字符串。
        /// </summary>
        internal static string 选择文件路径 {
            get {
                return ResourceManager.GetString("选择文件路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信 的本地化字符串。
        /// </summary>
        internal static string 通信 {
            get {
                return ResourceManager.GetString("通信", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信服务端 的本地化字符串。
        /// </summary>
        internal static string 通信服务端 {
            get {
                return ResourceManager.GetString("通信服务端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 通用电气 ] 的本地化字符串。
        /// </summary>
        internal static string 通用电气 {
            get {
                return ResourceManager.GetString("通用电气", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        internal static string 长度 {
            get {
                return ResourceManager.GetString("长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态地址 的本地化字符串。
        /// </summary>
        internal static string 静态地址 {
            get {
                return ResourceManager.GetString("静态地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string 颜色 {
            get {
                return ResourceManager.GetString("颜色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string 验证 {
            get {
                return ResourceManager.GetString("验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证图片异常 的本地化字符串。
        /// </summary>
        internal static string 验证图片异常 {
            get {
                return ResourceManager.GetString("验证图片异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证已停止 的本地化字符串。
        /// </summary>
        internal static string 验证已停止 {
            get {
                return ResourceManager.GetString("验证已停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证所有 的本地化字符串。
        /// </summary>
        internal static string 验证所有 {
            get {
                return ResourceManager.GetString("验证所有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证结果 的本地化字符串。
        /// </summary>
        internal static string 验证结果 {
            get {
                return ResourceManager.GetString("验证结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证选中 的本地化字符串。
        /// </summary>
        internal static string 验证选中 {
            get {
                return ResourceManager.GetString("验证选中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ 麦格米特 ] 的本地化字符串。
        /// </summary>
        internal static string 麦格米特 {
            get {
                return ResourceManager.GetString("麦格米特", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值不能为空 的本地化字符串。
        /// </summary>
        internal static string 默认值不能为空 {
            get {
                return ResourceManager.GetString("默认值不能为空", resourceCulture);
            }
        }
    }
}
